Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.communicator = "ssh"
  config.vm.hostname = "centos-basic.vm"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.memory = "4096"
  end
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end
