Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.communicator = "ssh"
  config.vm.hostname = "centos-mounted-dir.vm"
  config.vm.network "forwarded_port", guest: 80, host: 8000, id: "http", host_ip: "localhost", auto_correct: true
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.memory = "4096"
  end
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder "html/", "/vagrant/html", type: "virtualbox"
end
