
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.communicator = "ssh"
  config.vm.hostname = "centos-port-forward.vm"
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.memory = "4096"
  end
  config.vbguest.auto_update = false
  config.vm.provision "shell",
    inline: "yum install -y httpd; service httpd start"
end
